server:
  port: 8023
spring:
  data:
    mongodb:
      database: test
      uri: mongodb://prince:root@test-shard-00-00.cswuu.mongodb.net:27017,test-shard-00-01.cswuu.mongodb.net:27017,test-shard-00-02.cswuu.mongodb.net:27017/test?replicaSet=atlas-ofyv9a-shard-0&ssl=true&authSource=admin
